-- noinspection SqlNoDataSourceInspectionForFile

START TRANSACTION;

CREATE TABLE "IndexRecords" (
    "Word" text,
    CONSTRAINT "PK_IndexRecords" PRIMARY KEY ("Word")
);

CREATE TABLE "IndexRecords_Pages" (
    "Word" text NOT NULL,
    "PageId" integer NOT NULL
);

CREATE TABLE "Pages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Rank" integer NOT NULL,
    "Url" text NOT NULL,
    CONSTRAINT "PK_Pages" PRIMARY KEY ("Id")
);

COMMIT;
