-- noinspection SqlNoDataSourceInspectionForFile

BEGIN;

CREATE TABLE Term (
    Text text,
    WordId integer REFERENCES Word
);

CREATE TABLE Property (
    WordId text integer REFERENCES Word
    DocumentId integer REFERENCES Document
);

CREATE TABLE Document (
    DocumentId integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Url text NOT NULL,
    Date date NOT NULL,
    Size integer NOT NULL,
    Abstract text NOT NULL
);

CREATE TABLE Word (
    WordId integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    DocumentId integer REFERENCES Document
    Rank integer NOT NULL,
);

COMMIT;
